### ISSUE TITLE
Directly closing application leaves empty Virtual Desktop

### ISSUE THREAD

**Issue by Polunom** [Aetf/kwin-maxmize-to-new-desktop#3]
As the title says, directly closing a maximized window that's connected to a virtual desktop currently leaves an empty virtual desktop. It seems that @yuricbraga has already implemented a fix for this in [his fork](https://github.com/yuricbraga/kwin-macsimize/commit/a08acaca9d169a6e5e2241b0d72b47574a3731e0), so it'd be great if we could integrate his changes :)

**Comment by Aetf** [comment]
That commit was authored by me long time ago and also included here.

The actual problem is KWin crashes and restarts if the `clientRemoved` handler modifies the number of virtual desktops, leaving the empty virtual desktop not removed.

In the latest commit f05bb5ce794ddca813b956254a8d7380b6c6cde3 I fixed the crash but there are some caveats. KWin obviously have some bugs around its window activation and/or stack ordering, see [this](https://github.com/Aetf/kwin-maxmize-to-new-desktop#kwin-hangs-or-crashes-after-a-fullscreenedmaximized-window-is-directly-closed).

Anyway, this bug itself is fixed so I'm closing it.
